### ISSUE TITLE
与requirejs的debug变量冲突

### ISSUE THREAD

**Issue by andycall** [JacksonTian/eventproxy#62]
requirejs 中也定义了debug这个全局变量， 在用到eventproxy中会出现问题。造成报错

**Comment by JacksonTian** [comment]
requirejs的是哪里定义的？

**Comment by andycall** [comment]
那应该是我猜错了。。 但是的确存在这样的问题。比如：
```javascript
require(['eventproxy'], function(EventProxy){
	var ep = new EventProxy();

	ep.all('hello', function(){
		console.log('hello');
	});

	ep.emit('hello');
});
```

浏览器会报这样的错误。
![image](https://cloud.githubusercontent.com/assets/4409743/7247451/35728e5a-e83c-11e4-812f-69d368494776.png)

我找到您的源码有一些单词和报错信息很相近， 遂清除掉所有debug字段。 然后问题解决。
不知为啥， 当初猜测可能就是requirejs里面有啥定义。 不过刚才搜了一下，也没有。

**Comment by JacksonTian** [comment]
有地址么。

**Comment by andycall** [comment]
http://test.andycall.net/requirejs/O.html

**Comment by JacksonTian** [comment]
看起来是requirejs自己改了定义。。

**Comment by JacksonTian** [comment]
fixed in 1ed8a2b
