### ISSUE TITLE
proxy.after的一个每次都emit一个数组的场景

### ISSUE THREAD

**Issue by luoyjx** [JacksonTian/eventproxy#66]
我碰到一个场景，每次emit的data都是一个数组，并且这个数组最后要拿出来遍历后把所有子数组中的元素拿出来放到一起。
可以手动forEach然后concat实现。

加个类似于group的concat helper是否有用呢？

**Comment by JacksonTian** [comment]
对结果进行concat就好了。不用置入进去的。
