### ISSUE TITLE
How to call ep.after several times ?

### ISSUE THREAD

**Issue by NeilJee** [JacksonTian/eventproxy#67]
When the callback of ep.after is returned, I want to use ep.after function once more. Do I need to create a new ep object ? or I just can use it directly ?

Thank you

**Comment by JacksonTian** [comment]
Use new Instance please.

**Comment by NeilJee** [comment]
Actually I need to call up.after many times. Do I have to create many instances of ep ?

**Comment by JacksonTian** [comment]
If event name is same, use other instance. If not, continue use it is allowed. Use new instances is a good practice.

**Comment by JacksonTian** [comment]
The instance stored some data, when you use it, it will hold the memory. When you use other instances, the old instance can be GCed. So use old instance or new, depend on you current case.

**Comment by NeilJee** [comment]
Ok, Thank you

**Comment by alsotang** [comment]
When use same ep instance, avoid using duplicate names. Or you would meet some weird bugs due to its implement.

**Comment by JacksonTian** [comment]
use new instance of ep.

发自我的 iPhone
