### ISSUE TITLE
如何处理多路重复触发呢？

### ISSUE THREAD

**Issue by weiqingfei** [JacksonTian/eventproxy#71]
我这儿有个需求，两个超大文件内容对比，所以不能一次性读入内存，是用的fs.createReadStream方法，程序大概意思是这样的。

var fs = require('fs');
var readline = require('readline');
var stream = require('stream');
var EventProxy = require('eventproxy');

var ep = new EventProxy();
ep.tail('line1','line2',function(line1, line2){
    compare(line1,line2);
});

var instream1 = fs.createReadStream('a.txt');
var instream2 = fs.createReadStream('b.txt');
var outstream1 = new stream();
var outstream2 = new stream();
var rl1 = readline.createInterface(instream1, outstream1);
var rl2 = readline.createInterface(instream2, outstream2);
rl1.on('line', function(line) {
  ep.emit('line1', line);
});
rl2.on('line', function(line) {
  ep.emit('line2', line);
});

显然这个地方用ep.tail是不行的，如何实现？

**Comment by JacksonTian** [comment]
对比文件可以先用两个read stream和sha1的方式算出文件的hash。再比较hash是否相同即可。

**Comment by weiqingfei** [comment]
不好意思，是我没说清楚，实际上这是两个csv文件，我比较的不是整个文件是否相同，而是哪一行的哪一个项目不同。
打个简单的比方，
a文件内容：
aaa1,bbb1,ccc1
aaa2,bbb2,ccc2

b文件内容：
aaa1,bbb1,ccc1
aaa2,bcb2,ccc2

我要的结果是第二行的第二个字段是不同的，打印出的结果大概是这样的
第2行，文件a：bbb2/文件b：bcb2

当然两个文件都非常的大，需要一行行来比较。

**Comment by fengmk2** [comment]
这个需求跟ep没有关系吧

**Comment by weiqingfei** [comment]
不明白你说的没关系是什么意思，ep实现了一次性的并行准备到串行处理的功能。而我需要连续性的，就像我最开始写的，两路stream并行读取各自的line，然后比较这两个line里的内容。

当然，如果可以提供ep之外的解决方案也非常感谢。

**Comment by JacksonTian** [comment]
你可以用child_process去调用diff来对比更好。

**Comment by weiqingfei** [comment]
好吧，老实说这只是一个例子，我其实更想知道，如果是多路重复过来数据，ep是否有可能处理，比如网络数据，比如数据库抽出的数据。

**Comment by JacksonTian** [comment]
不管怎么处理，先要抽象出事件。再按情况来使用ep的API.
