### ISSUE TITLE
内存回收问题

### ISSUE THREAD

**Issue by vylan** [JacksonTian/eventproxy#74]
你好，

如果我监听了某个事件, 如`ep.on('evt',function(){})`，那么这里的ep所占用的内存是如何回收的？removeAllListeners是不是可以解除所有的事件引用？  谢谢

**Comment by JacksonTian** [comment]
ep自身的回收就是GC正常回收而已。

removeAllListeners只是删除所有事件而已。

**Comment by vylan** [comment]
您的意思是说，ep监听的事件并不会增加对ep的引用，并不影响GC对ep本身的回收？

**Comment by JacksonTian** [comment]
嗯。

**Comment by vylan** [comment]
好的，谢谢。
