### ISSUE TITLE
Error: Can't set headers after they are sent

### ISSUE THREAD

**Issue by elevensky** [JacksonTian/eventproxy#75]
场景
一个ajax post数据的验证的功能。

```
$.ajax({
  type: "POST",
  url: url,
  data: $("#sendForm").serialize(),
    success: function(data) {
  },
})
```

后端接收代码：
![后端代码](https://dn-cnode.qbox.me/FvCStJHO5HDM8rDsuQxUQoXPZRx5)

第一次点击post后验证是正常返回的，后面在重复点击就会报错：
服务器响应： 500 Can't set headers after they are sent.

用的eventproxy做的流程控制，换成直接res.send()就好了，不知道是不是eventproxy的问题。

**Comment by JacksonTian** [comment]
服务端代码写得有问题。
