### ISSUE TITLE
关于express的res.send问题

### ISSUE THREAD

**Issue by blackmatch** [JacksonTian/eventproxy#78]
场景：写一个后台接口（express），需要修改几张表，修改表的顺序分先后，所以用eventproxy控制并发。在ep.once或者ep.all的回调里调用res.send方法不生效，调用接口后得不到任何返回。有人遇到过这个问题么？求指导。

**Comment by JacksonTian** [comment]
有顺序的调用建议你用Promise把。

**Comment by JacksonTian** [comment]
有顺序的调用建议你用Promise把。

**Comment by blackmatch** [comment]
@JacksonTian 谢谢你的建议，是我的失误，在ep.all的回调里面是可以执行res.send的，我之前一个接口一直是用浏览器来发请求调试，发现怎么都拿不到response，也没注意看控制台输出。最后发现是因为跨域问题。把跨域问题解决就能成功拿到response了。题外话：用postman调试接口不会出现跨域问题，我就是偷懒，因为这个接口里面的参数是多个对象，所以用jQuery来发请求了。。。

**Comment by JacksonTian** [comment]
有顺序的调用建议你用Promise把。

**Comment by JacksonTian** [comment]
有顺序的调用建议你用Promise把。

**Comment by JacksonTian** [comment]
有顺序的调用建议你用Promise把。
