### ISSUE TITLE
Bagpipe有可能被并过来用于实现类似async中的limit吗？

### ISSUE THREAD

**Issue by jeneser** [JacksonTian/eventproxy#79]
当我们需要从远程服务器获取资源时，高并发效率固然高，但并发量过多时，服务器肯定会有问题，就需要控制并发数量了。
目前API里并没有控制并发数量的方法，
在 issue #70 中，说配合bagpipe使用，那么你们肯定想过这个问题
https://github.com/JacksonTian/bagpipe

有一点不明白，控制并发数量也应该是比较常见的场景吧，那么为何不直接提供这个方法呢？(又可以省去一条依赖了，哈哈😄)，把bagpipe分离出来又是何用意呢？或者是Bagpipe有可能被并过来用于实现类似async中的limit吗？请指点！

**Comment by JacksonTian** [comment]
没有必要合并过来啊，那么小巧的东西，直接用就好了。
