### ISSUE TITLE
[跨模块emit]_callbacks和_fired缓存起来

### ISSUE THREAD

**Issue by PetersonLian** [JacksonTian/eventproxy#80]
如果存在模块emit的情况，目前貌似只能，将EventProxy的实例在两个模块之间传递（或者模块的方法调用的时候传入）。
怎么处理跨模块emit的情况？
我在A里头监听，然后在B里头emit。同时A require B。
我只是一个刚使用eventproxy的，不清楚是否已经有跨模块的支持？

**Comment by JacksonTian** [comment]
不应该这样用。

**Comment by PetersonLian** [comment]
@JacksonTian 
我目前的使用方式是：
A里头，require B，然后获得一个exports对象，调用其中譬如hiB函数；
在A里头，调用hiB的时候，给hiB传入一个callback函数。在callback函数里头调用emit。
譬如

    require(B).hiB(function thisIsCB(){eventProxyInstanceDefinedAtA.emit('xxx')});

这样的使用方式，是不对的是吧？
