### ISSUE TITLE
EventProxy.prototype.throw在低版本IE上报错

### ISSUE THREAD

**Issue by joe511230** [JacksonTian/eventproxy#82]
报错信息：缺少标识符
throw是其关键字，在低版本IE（仅测试IE8/IE7）上不能作为标识符，
低版本IE上，不能使用关键字作为对象的key。

**Comment by JacksonTian** [comment]
1. 不会去刻意支持 IE 低版本。
2. 如果坚持要支持，希望能主动 PR。
