### ISSUE TITLE
http://eventproxy.html5ify.com/ 访问不了了

### ISSUE THREAD

**Issue by ghost** [JacksonTian/eventproxy#84]
想看注解文档，发现`http://eventproxy.html5ify.com/ `访问不了了

**Comment by JacksonTian** [comment]
续费域名了。

**Comment by KK-AI-LL** [comment]
@JacksonTian  注解文档又看不了了～ http://html5ify.com/eventproxy/eventproxy.html

**Comment by 18boys** [comment]
已收到,稍候会处理best wish~
